### ISSUE TITLE
Plugin appears to solve https://github.com/raptor2101/Mediathek/issues/67

### ISSUE THREAD

**Issue by Wikinaut** [YggdrasiI/plugin.video.simple_mediathek_de#1]
Hi @YggdrasiI , your plugin appears to be a solution for the issue I filed as https://github.com/raptor2101/Mediathek/issues/67 . Nice work, and I will try yours as soon as possible in the next weeks.

**Comment by YggdrasiI** [comment]
Yes, it should be an solution for your use case.
From programmers perspective (if you want integrate access to MediathekView data) the Api to MediathekViewWeb, mentioned [here](https://forum.mediathekview.de/post/1191) would also be an good approach.
