### ISSUE TITLE
DB Update

### ISSUE THREAD

**Issue by MyLive** [YggdrasiI/plugin.video.simple_mediathek_de#10]
Is it possible to update the DB ( external MySQL ) from any other Host without the Mediathek plugin.

Reason is that the Kodi System is slow and the Update take a long time.
I have a NAS with more Power and would like to update the Mediathek Database on this Host

Thanks a lot :-)

**Comment by vitusson** [comment]
I guess you are wrong here, and wanted to post there https://github.com/mediathekview/MediathekView
This plugin here uses no MySQL database. ;-)

**Comment by YggdrasiI** [comment]
Hello,

updating the database is possible, but only works if both systems uses the same software version (The format is binary and could change over the time.)

Just copy the plugin folder on you (linux based) Nas and cd into
``plugin.video.simple_mediathek_de/root/bin ``
Then call  ``./simple_mediathek --folder /some/folder update`` 
and copy the files from /some/folder to
 ``$HOME/.kodi/userdata/addon_data/plugin.video.simple_mediathek_de``
on your kodi system


Finally I want note that the update should be fast on almost every system. :) Offloading the workload just made sense on RPi1 or to share data between multiple systems.
