### ISSUE TITLE
OSMC on Raspberry Pi

### ISSUE THREAD

**Issue by Wikinaut** [YggdrasiI/plugin.video.simple_mediathek_de#2]
Hi, ich benutze OSMC auf dem Raspberry Pi. Es wäre nett, wenn Du die dafür (für Dein Plugin) notwendigen Installationsschritte aufschreiben könntest oder Dein Plugin in das Video-Addon-Repo einstellen könntest.

Leider weiß ich (noch) nicht, wie man es zusammenbaut, ob das auf dem Zielsystem passieren muss, oder ob man es auf einem anderen Linuxsystem "cross-compilieren" kann, was natürlich genial wäre.

**Comment by YggdrasiI** [comment]
Hallo,

OSMC habe ich selber bisher nie benutzt, aber da die Binaries für die RPi's bereits vorkompiliert beiliegen, sollte es ausreichen, das Git-Repo auf deinem PC zu klonen und das gesamte Verzeichnis anschließend (laut https://osmc.tv/wiki/general/exploring-kodi-file-locations/ ) auf dem RPi nach /home/osmc/.kodi/addons/ zu kopieren.

Cross-Compilieren der Binaries habe ich nicht ausprobiert, aber aufgrund der geringen Abhängigkeiten ist es kein Problem das Binary unter Raspian zu kompilieren und dann auf andere System zu übertragen.

P.S. Da es im Readme noch fehlt. Ein per SSH abgesetztes 'kodi-send -a 'RunScript(plugin.video.simple_mediathek_de, update_db)'
nach der Installation aktualisiert die lokalen Daten am schnellsten.

**Comment by Wikinaut** [comment]
@YggdrasiI ich muss mich wohl doch genauer mit dem OSMC auf dem Raspi auseinandersetzen. Ich werde meine Erfahrungen ggfs. hier dokumentieren, bzw. zurückmelden.

**Comment by Wikinaut** [comment]
Etwas scheint noch zu fehlen.

Hier meine Schritte (per ssh auf dem Raspi):

```
ssh osmc@raspi
sudo su
cd /home/osmc/.kodi/addons
apt install git build-essential make cmake zip
git clone https://github.com/YggdrasiI/plugin.video.simple_mediathek_de
cd /home/osmc/.kodi/addons/plugin.video.simple_mediathek_de
make native
make addon
kodi-send -a "UpdateLocalAddons"
# vorsichtshalber:
reboot now
```

Probleme: 
* Das Plugin ist unter "Video Addons" nicht gelistet.
* Installation des Zip-Files schlägt fehl mit der Meldung "Zip-File hat nicht die korrekte Struktur."

**Comment by YggdrasiI** [comment]
Ah, unter der neuen Kodi-Version muss man manuell installierte Addons explizt freischalten... Das habe ich nirgends erwähnt
"3. (New in Krypton…) Allow addons from unknown sources in Preferences>System>Addons"

**Comment by Wikinaut** [comment]
Das war schon standardmäßig eingeschaltet. Hilft nicht!

**Comment by YggdrasiI** [comment]
Um welche Kodi-Version handelt es sich und kannst du Fehler im Log erkennen/es hier hochladen?
Das Log befindet sich wahrscheinlich unter /home/osmc/.kodi/temp/kodi.log

**Comment by Wikinaut** [comment]
http://dpaste.com/2QXKV5D.txt

**Comment by Wikinaut** [comment]
bitte beachte, dass auch die Installation über das lokal gebaute Zipfile nicht geht, die Installation des Zip-Files schlägt fehl mit der Meldung "Zip-File hat nicht die korrekte Struktur."

**Comment by YggdrasiI** [comment]
Im Log stand nichts, aber ich werde mal auf Version 17.1 updaten und die Zip-Installation nachstellen. Die oben geposteten Schritte sind korrekt.

**Comment by Wikinaut** [comment]
Jaaaaa, bitteee gleich.....

**Comment by Wikinaut** [comment]
ich sende Dir auch eine Spende

**Comment by YggdrasiI** [comment]
Ich kann den Fehler leider nicht nachstellen.
Nach dem Update auf 17.1, läuft die Installation aus [diesem](https://forum.mediathekview.de/uploads/files/1491600168327-plugin.video.simple_mediathek_de.zip) Zip bei mir durch und das Plugin wird danach in den Video-Addons angezeigt

**Comment by Wikinaut** [comment]
Ja, mit _dieser_ Datei https://forum.mediathekview.de/uploads/files/1491600168327-plugin.video.simple_mediathek_de.zip ging es.
Es ging nicht mit der von mir lokal erzeugten (git-Version f2691c8992bd553af998e5f93184e614bd0a7c21 ) und mit Deiner https://forum.mediathekview.de/uploads/files/1490783483149-plugin.video.simple_mediathek_de.zip von https://forum.mediathekview.de/topic/193/mediatheken-plugin-f%C3%BCr-kodi )

**Comment by Wikinaut** [comment]
Vielleicht bekommst Du raus, was der Unterschied ist.

**Comment by YggdrasiI** [comment]
Danke für das Feedback. Ich kann keinen relevanten Unterschied zwischen der beiden Zip-Versionen von mir feststellen. Einziger Verdachtsmoment, der mir einfällt, wäre eine abweichende Verschachtelungstiefe im Zip.  Hattest du dein Zip mit 'make addon' erstellt oder per Hand das Repo-Verzeichnis gezippt?

**Comment by Wikinaut** [comment]
Ich hatte mein Zip per `make addon` erstellt, dann mit `sudo cp *.zip /home/osmc` in ein Verzeichnis kopiert, das auf dem TV-GUI per `Einstellungen > Addon-Browser > Lade Addon aus Zipfile` sichtbar ist, und dann darüber angeklickt.


Dann kam die schon oben genannte kurz sichtbare Meldung "Zip-File hat nicht die korrekte Struktur."

**Comment by YggdrasiI** [comment]
Beim Erstellen einer neuen Version konnte ich den Fehler jetzt reproduzieren. Ursache ist der Unzip-Mechanismus von Kodi, der nicht mit symbolischen Links im Archiv umgehen kann. Außerdem wird Dateien beim Unzipen ihr +x-Flag entzogen.
Entferne ich die Symlinks beim Packen verdoppelt sich zwar die Dateigröße, aber Kodi ist zufrieden.

Für beide Probleme habe ich das Pythonskript um eine Methode erweitert, die nach Installation des Addons die Probleme löst. (Die nicht auftreten, wenn man das Archiv mit unzip entpackt...)

**Comment by Wikinaut** [comment]
I confirm that 6d45e1f2c360fc210fc02ec5b4ed4546889126d6 fixes this (generated zip file can be installed after having moved from `~/.kodi/addon` subdirectory to the `~` home directory.

Remark: on the OSMC GUI, the addon-zip-filebrowser does not allow selection of files in hidden directories. This is why the zip must be moved (or copied) to a selectable directory like the user home directory.

If possible, I suggest that `make addon` creates the zip file there.
