### ISSUE TITLE
[Vorschlag] "List" View als Standard setzen

### ISSUE THREAD

**Issue by Wikinaut** [YggdrasiI/plugin.video.simple_mediathek_de#3]
UPDATE:
ich habe den Titel dieses Issues geändert auf  [Vorschlag] "List" View als Standard setzen #3

**Comment by Wikinaut** [comment]
Ich habe hier immer (auf dem Raspi) die Anzeige mit breiten Blöcken (Symbolen) - wie kann ich das für alle Seiten des Plugins auf den Anzeigetyp "Liste" umstellen ?

**Comment by YggdrasiI** [comment]
Die Standard-Ansicht eines Skins muss nicht die Listen-Ansicht sein. Ob es gerechtfertigt ist aufgrund des Addon-Aufbaus hier immer die Listenansicht vorzugeben muss ich mir noch überlegen, aber für das aktuelle Problem update bitte die Datei addon.py zu folgender (unstable-branch): https://github.com/YggdrasiI/plugin.video.simple_mediathek_de/blob/unstable/addon.py

Damit sollte innerhalb des Addons immer die Listenansicht gewählt werden. Aufgrund des Caches kann es sein, dass die Einstellung erst beim zweiten Aufruf eines Untermenüs berücksichtigt wird.

**Comment by Wikinaut** [comment]
Ich habe das neue addon.py vom unstable branch geladen. Folgendes Verhalten bleibt komisch:

(steps to reproduce)

* Setze eine neue Suche (Beispielsweise war die vorherige Suche "barbarossaplatz", und die neue Suche ist "mitternachtsspitzen".
* Nach dem Senden des Strings (per "KORE"-App vom Smartphone) kommt zuerst weiterhin immer die BLOCK-Ansicht.

Das ist nicht schön und verwirrt mich sehr.

**Comment by YggdrasiI** [comment]
Ich bin zum Testen vom Confluence-Skin zum jetztigen Standard-Skin (Estuary) zurückgekehrt. Dort bleibt die Ansicht beim Testen im Listen-Modus, aber
vielleicht habe ich das Problem noch nicht richtig erfasst.
Hängt die Ansicht in der KORE-App mit der Ansicht auf dem Hauptbildschirm zusammen oder ist diese unabhängig?

**Comment by Wikinaut** [comment]
Ich kann das derzeit nicht testen, melde mich, wenn es wieder geht.

**Comment by Wikinaut** [comment]
So, da bin ich wieder, bereit zum weiteren Debuggen und Testen.

Ich habe die aktuelle Masterversion https://github.com/YggdrasiI/plugin.video.simple_mediathek_de/commit/6d45e1f2c360fc210fc02ec5b4ed4546889126d6 installiert.

Da sehe ich wieder keine "List"view

* nach der Eingabe des Suchstrings kommt lästigerweise wieder die Symbolanzeige
* nach Klicken auf "Suchen" werden die Ergebnisse auch nur als Symbolanzeige angezeigt.


Was könnte ich wo abändern, damit _immer_ die Listenanzeige kommt ?

**Comment by YggdrasiI** [comment]
Hallo, ich habe jetzt die Entwicklung des Addons wieder aufgenommen und
 in den Einstellung eine Option eingefügt mit der man
die Ansicht als Breite Liste forcieren kann. Im Plugin wird dann bei jedem Start
``xbmc.executebuiltin(u"Container.SetViewMode(51)"`` 
ausgeführt.
Leider befürchte ich, dass ich es damit weiterhin zwar bei mir funktioniert, aber bei dir immer noch in die Block-Ansicht wechselt. Das liegt dann aber eher an Einfluss von außen (Kore-App, anderes Plugin?!)

Mit freundlichen Grüßen, 
Olaf

**Comment by Wikinaut** [comment]
Danke erstmal für Wiederaufnahme der Arbeit am Plugin. Ich werde mir die neue Version zusammenbauen, und melde mich dann wieder.

**Comment by YggdrasiI** [comment]
Nach der Installation von OSMC und des dort verwendeten Skins konnte ich das Problem besser nachvollziehen. Im Unterschied zum Confluence-Skin erreicht man mittels ```xbmc.executebuiltin("Container.SetViewMode(50)``` nichts.

Nachdem ich den Inhalt der Verzeichnisse aber über
 ```xbmcplugin.setContent(addon_handle, "files")```  definiert habe ("movies" hat nicht den gleichen Effekt!)
bevorzugt skin.estuary und skin.osmc die Listen-Ansicht.

Das neue [Release](https://github.com/YggdrasiI/plugin.video.simple_mediathek_de/releases/tag/81469617c) setzt die ausgebesserte Variante ein.
