### ISSUE TITLE
Suchstring mit Non-ASCII (Beispiel: "charité" bei Eingabe in der "Kore" Fernbedienungs-App) verursacht Fehlermeldung; "charite" findet nichts.

### ISSUE THREAD

**Issue by Wikinaut** [YggdrasiI/plugin.video.simple_mediathek_de#5]
Update:
Ich benutze für die Stringeingabe die Kore v.2.20 Fernbedienungs-App https://play.google.com/store/apps/details?id=org.xbmc.kore&hl=en auf meinem Android-Phone. Möglicherweise ist diese App "Schuld".

#### Bug: Suchstring mit Non-ASCII verursacht Fehler
* Wenn ich nach `charité` suche: kommt "**Mediatheken** **Fehler**"meldung (Logfile siehe unten).
* Wenn ich nach `charite` suche: kommt *kein* Ergebnis; die Suche scheint also derzeit eine *exakte* Suche zu sein, die auf die laxe (falsche) Schreibweise kein Ergebnis liefert.
Verbesserungsvorschlag: Die Suche sollte benutzerfreundlich *sonderzeichenirrelevant* sein (ä á à â usw. ==> a usw.).
* Workaround: ich suche nach `charit`, um Ergebisliste zu erhalten, und dann manuell weiterzusuchen.

Version:
https://github.com/YggdrasiI/plugin.video.simple_mediathek_de/commit/6d45e1f2c360fc210fc02ec5b4ed4546889126d6

Logfile:
```
11:06:11.217 T:1190614000  NOTICE: Previous line repeats 1 times.
11:06:11.218 T:1190614000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: execv() arg 2 must contain only strings
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/addon.py", line 1214, in <module>
                                                (exit_code, data) = call_binary(search_args)
                                              File "/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/addon.py", line 494, in call_binary
                                                stderr=subprocess.PIPE)
                                              File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
                                                raise child_exception
                                            TypeError: execv() arg 2 must contain only strings
                                            -->End of Python script error report<--
11:06:12.642 T:1959089072   ERROR: GetDirectory - Error getting plugin://plugin.video.simple_mediathek_de/?j=%7b%22mode%22%3a%20%22start_search%22%2c%20%22prev_mode%22%3a%20%22main%22%7d
11:06:12.645 T:1959089072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.simple_mediathek_de/?j=%7b%22mode%22%3a%20%22start_search%22%2c%20%22prev_mode%22%3a%20%22main%22%7d) failed
```

**Comment by YggdrasiI** [comment]
Hallo, grundsätzlich stimme ich dir zu. Die Buchstaben sollten für die Suche normalisiert werden und ihre Azkente verlieren. Die Umlaute nehme ich von der Regel allerdings aus.
Im konkreten Fall funktioniert die Suche, mit der von dir oben angegebenen Version, allerdings sowohl auf der Konsole als auch in Kodi, wenn ich nach „Charité“ suche.

`cd .kodi/addons/plugin.video.simple_mediathek_de/root/bin
./simple_mediathek --search --title "Charité" 2>/dev/null
{ "found": [
	{"id": 15069, "title": "Folge 6: Zeitenwende", 
		"ibegin": 1492539300, "begin": "18. Apr. 2017 20:15", "iduration": 2880, "ichannel": 2, "channel": "ard", "anchor": 1872312},
	{"id": 15077, "title": "XL-Vorschau auf \"Charité\"", 
		"ibegin": 1490123700, "begin": "21. Mar. 2017 20:15", "iduration": 120, "ichannel": 2, "channel": "ard", "anchor": 1873296},
	{"id": 31756, "title": "Neue ARD-Serie Charité startet", 
		"ibegin": 1490121000, "begin": "21. Mar. 2017 19:30", "iduration": 240, "ichannel": 2, "channel": "ard", "anchor": 3918229},
	{"id": 74690, "title": "\"Charité\" - die neue Eventserie der ARD", 
		"ibegin": 1489698900, "begin": "16. Mar. 2017 22:15", "iduration": 360, "ichannel": 2, "channel": "ard", "anchor": 17538382},
	{"id": 127134, "title": "\"Charité\" - die neue Eventserie der ARD", 
		"ibegin": 1489698900, "begin": "16. Mar. 2017 22:15", "iduration": 382, "ichannel": 13, "channel": "rbb", "anchor": 36990057},
	{"id": 165574, "title": "Arzt: Mehr Tumor-Erkrankungen durch Autoabgase - Im Interview Prof. Christian Witt, Leiter Lungenklinik Charité", 
		"ibegin": 1488193680, "begin": "27. Feb. 2017 12:08", "iduration": 119, "ichannel": 19, "channel": "zdf", "anchor": 52776175}
]}
`

**Comment by Wikinaut** [comment]
Ich benutze allerdings - und trage das oben auch noch gleich nach - die Kore v.2.20 Fernbedienungs-App https://play.google.com/store/apps/details?id=org.xbmc.kore&hl=en auf meinem Android-Phone. Möglicherweise ist diese "Schuld".

Umso wichtiger wäre das von mir vorgeschlagene Zeichenmapping!

**Comment by Wikinaut** [comment]
@YggdrasiI Wann könntest Du das implementieren, ich habe allergrößtes Interesse daran. Und: vielleicht solltest Du die Umlaute doch auch "mappen", aber das kann man später ja noch sehen.

Wie kann ich Dir eine Spende überweisen ? Hast Du eine Bitcoinadresse ?

**Comment by YggdrasiI** [comment]
Hallo Wikinaut,

 ich habe zwei neue Commits erstellt (@341fc36). Der erste Commit kümmert sich um das Mapping der Buchstaben (erfordert Neukompilieren) und der zweite könnte das Problem mit dem Suchstring bei der Eingabe mit KORE lösen.
Ich habe zur Sicherheit noch eine Konvertierung der Eingabeargumente in den unicode-Typ eingebaut.
Da ich leider keine Infos zum Encodierungstyp von KORE fand, musst du allerdings noch ausprobieren, ob dies schon als Lösung ausreicht. 

@Spende: Sehr gerne und vielen Dank :) Falls Paypal auch eine Option darstellt würde ich sie auf meiner Commit-Mailadresse,  funwithkinect@googlemail.com entgegen nehmen. Mit Bitcoin muss ich mich erst noch außeinander setzen.

**Comment by Wikinaut** [comment]
Ich teste es am Montagmorgen.

**Comment by Wikinaut** [comment]
Mit der aktuellen Version 341fc36abd74dc190450a4ad56f0695388f795f8

gibt leider schon das Update der Filmliste einen Fehler, Logfile:

```
12:42:06.887 T:1560278000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/addon.py", line 1003, in <module>
                                                bForceFullUpdate=False)
                                              File "/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/addon.py", line 375, in update_db
                                                js = json.loads(data)
                                              File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
12:42:07.323 T:1958151088   ERROR: GetDirectory - Error getting plugin://plugin.video.simple_mediathek_de/?j=%7b%22mode%22%3a%20%22update_db%22%2c%20%22prev_mode%22%3a%20%22None%22%7d
12:42:07.325 T:1958151088   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.simple_mediathek_de/?j=%7b%22mode%22%3a%20%22update_db%22%2c%20%22prev_mode%22%3a%20%22None%22%7d) failed
12:42:12.745 T:1503654896   ERROR: Unable to find plugin
12:42:12.745 T:1958151088   ERROR: GetDirectory - Error getting plugin://
12:42:12.746 T:1958151088   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
```

**Comment by YggdrasiI** [comment]
Bitte probiere es noch einmal. Ein dummer Fehler meinerseits aufgrund fehlenden Tests.
Am besten stelle ich eine Liste von Plugin-Urls, siehe Fehlermeldung, zusammen, um das zukünftig in einem Skript testen zu können.

Gruß YggdrasiI

**Comment by Wikinaut** [comment]
So, also... erste Verbesserungen deutlich sichtbar:

* das Laden der Filmliste geht nun wieder wie es soll.
* Suchstring "charite" (per Keyboard am Raspi eingetippt) gibt jetzt auch Ergebnisse. Dazu gleich noch ein anderes Issue, da https://mediathekviewweb.de/#query=charite 13 Ergebnisse liefert, aber Dein Programm nur 6 (bei gleichem Suchstring "charite").

Was ich leider _nicht_ testen konnte- weil meine Kore-App (mehrere Geräte, mehrere Versionen) im Netzwerk den Raspi nicht mehr findet (WLAN oder LAN) -

* ist die Kore-App-Stringeingabe von "charité"
* die Keyboardeingabe von "charité" (weil das OSMC irgendwie die Spezialzeichen meiner deutschen Tastatur nicht erkennt. Muss ich nochmal per ssh prüfen, was dafür anders einzustellen ist.

Dazu melde ich mich, wenn die genannte Hier-Probleme gelöst habe.

**Comment by YggdrasiI** [comment]
Das Problem sollte nun in allen Ausprägungen behoben sein.
Die Topic-Strings werden nur korrekt jedem Eintrag zugeordnet und kombinierte Zeichen wie è, ç, Å werden auf ihren Grundbuchstaben zurückgeführt (die vollständige Liste ist in native_source/helper.c zu finden).
