### ISSUE TITLE
Suche nach "charite" gibt nur sechs Ergebnisse mit dem Plugin; MediathekViewWeb gibt aber 13 Ergebnisse.

### ISSUE THREAD

**Issue by Wikinaut** [YggdrasiI/plugin.video.simple_mediathek_de#6]
Wieso ergeben sich beim *Plugin* weniger Ergebnisse, bei offenbar gleichem Filmlistenstand ? (20170424-1515)

**Comment by YggdrasiI** [comment]
Ich tippe auf den verbesserten Algorithmus von Bagbag bei MediathekviewWeb. Dieses Plugin nutzt nur die aktuelle Fassung der Filmliste. Wenn man nun einen Beitrag herauspickt, der bei ihm dabei ist und hier nicht, sieht man, dass das Schlüsselwort Charité im Eintrag überhaupt nicht vorkommt.
Er greift beim Parsing daher auch auf ältere Versionen zurück und da gab es dann vermutlich mal einen passende Version. 

`,"X":["","","Folge 3: Das Licht der Welt","28.03.2017","20:15:00","00:47:00","703","Paul Ehrlichs Frau ist hochschwanger, doch der Hebamme gelingt es nicht, das Kind zu wenden. Als sich die Situation zuspitzt und das Kind keine Herztöne mehr zeigt, kann nur noch der einzig im Krankenhaus verbliebene Chirurg helfen.","http://pd-videos.daserste.de/int/2017/03/14/5eb33453-8604-44f6-a9ad-227b9c2e3701/960-1.mp4","http://www.ardmediathek.de/tv/Charit%C3%A9/Folge-3-Das-Licht-der-Welt/Das-Erste/Video?bcastId=41166222&documentId=41683708","http://www.ardmediathek.de/subtitle/147639","","81|512-1.mp4","","","","1490724900","","","false"]
`
Hier zum Vergleich der Eintrag bei Folge 6. Hier ist der Themen-String (vorne) nicht leer sondern passenderweise „Charité“.
` ,"X":["","Charité","Folge 6: Zeitenwende","18.04.2017","20:15:00","00:48:00","723","Kochs wissensch       aftliches Versagen bringt auch die Forschung seiner Mitarbeiter in Misskredit. Zur Hochzeit mit Hedwig erscheinen nur die engsten Freunde, zu denen auch Ida und Ehrlich gehören.","http://pd-videos.daserste.de/int/2017/03/14/f7071fb6-003b-4bdf-b287-5c7322421f89/960-1.mp4","http://www.ardmediathek.       de/tv/Charit%C3%A9/Folge-6-Zeitenwende/Das-Erste/Video?bcastId=41166222&documentId=42103192","http:       //www.ardmediathek.de/subtitle/159598","","81|512-1.mp4","","","","1492539300","","","false"]
`

Das Problem ist also die Qualität der Eingangsdaten. Dies auf Pluginebene zu verbessern ist meiner Meinung nach keine gute Idee. Es wäre dann vermutlich besser und einfacher die Suche an die Webapi von MediathekviewWeb weiter zu reichen.

**Comment by Wikinaut** [comment]
@YggdrasiI 

Danke für die Erklärung.

> Es wäre dann vermutlich besser und einfacher die Suche an die Webapi von MediathekviewWeb weiter zu reichen.

Auch gut, aber das ist dann eine weitere Abhängigkeit. Man (ich) muss aber sagen, dass @bagbag eine tolle Liste produziert, so je besser, desto besser.....

**Comment by bagbag** [comment]
> Er greift beim Parsing daher auch auf ältere Versionen zurück und da gab es dann vermutlich mal einen passende Version.

Das mache ich (noch) nicht, in Zukunft möchte ich jedoch auch ein Archiv anbieten :)
Ich nutze die jeweils vorherige Filmliste lediglich um ein Delta-Update zu erzeugen, das das Indexieren um ein vielfaches beschleunigt und vor allem keine Downtime der Suche mehr mit sich bringt.

Die Filmliste ist so aufgebaut, dass wenn der Sender oder das Thema leer ist, der jeweils letzte Eintrag mit ausgefüllten Daten zählt.

also:

["ARD", "Tagesschau", "10.12"]
["", "", "11.12"] <- ist ebenfalls ARD, Tagesschau
["", "", "12.12"] <- ist ebenfalls ARD, Tagesschau
["", "", "13.12"] <- ist ebenfalls ARD, Tagesschau
["", "Sportschau", "10.12"] <- ist ebenfalls ARD
["", "", "11.12"] <- ist ebenfalls ARD, Sportschau
["", "", "12.12"] <- ist ebenfalls ARD, Sportschau
["", "", "13.12"] <- ist ebenfalls ARD, Sportschau
["ZDF", "Morgenmagazin", "10.12"]
["", "", "11.12"] <- ist ebenfalls ZDF, Morgenmagazin
["", "", "12.12"] <- ist ebenfalls ZDF, Morgenmagazin
["", "", "13.12"] <- ist ebenfalls ZDF, Morgenmagazin

Ich hoffe du hast es verstanden.


@Wikinaut 
Ich erlaube mir zu sagen, dass das eine ganz akzeptable Abhängigkeit wäre 😃 


@YggdrasiI 
Mein Angebot mit einer API steht immer noch. Und da ich gerade alles neu programmiere, kannst du auch gerne mit Feature Requests kommen, die ich einbauen soll.

**Comment by Wikinaut** [comment]
@YggdrasiI @bagbag Ihr seid Klasse! Bitte arbeitet zusammen, ich freue mich schon auf (OSMC=Browser) MediathekView mit Eurer Software.

**Comment by YggdrasiI** [comment]
@bagbag:
Hallo, falls dein Angebot zur API noch steht: Ich habe damit begonnen und dafür einen neuen Issue eröffnet: https://github.com/YggdrasiI/plugin.video.simple_mediathek_de/issues/8
Das Abfragen nach Title/Topic, Description oder Channel sollte bereits wie gewünscht funktionieren.

Mit freundlichen Grüßen,
Olaf

**Comment by bagbag** [comment]
Klar, das steht noch. Hab dir in dem Ticket geschrieben.
